### ISSUE TITLE
学习案例study.js

### ISSUE THREAD

**Issue by gapsaras** [Foveluy/Luy#3]
你好，最近在知乎上看到大神的这个项目，今天试了下学习案例`/study`，发现其中的`createElement.js`文件，虽然在`study.js`中引用了，但是却没用使用，不懂为什么？另外如果没用使用`createElement.js`，那vnode的生成是怎么做的呢，使用babel转的吗？

麻烦大神给解答一下。

**Comment by gapsaras** [comment]
@215566435 谢谢大神的及时回复，我的理解是：`createElement`会被babel使用，作为生成vnode的实现方法，相当于babel对外提供的一个可被用户覆盖的方法，不知是不是这样？

**Comment by 215566435** [comment]
@gapsaras 是的，没错。

**Comment by Foveluy** [comment]
修复
